[tool.poetry]
name = "llama-torchtune-finetuning"
version = "0.1.0"
description = ""
authors = ["Outerbounds"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torchtune = "^0.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
